name: Wakatime Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: mdyeamin/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY = 542e562f-c003-4d68-93d9-6b56dbbcaeca}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN = 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 }} # only required if using the action in repository other than profile